# Generated by Django 2.1.1 on 2019-11-29 21:13

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Historical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('stock', models.CharField(max_length=15)),
                ('series_x', django.contrib.postgres.fields.ArrayField(base_field=models.DateField(), size=None)),
                ('series_y', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('buy_price', models.FloatField()),
            ],
        ),
    ]
