# Generated by Django 2.1.1 on 2019-11-29 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historical',
            name='buy_qty',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
