# Generated by Django 2.1.1 on 2019-11-29 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_historical_buy_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='historical',
            name='current',
            field=models.FloatField(default=100),
            preserve_default=False,
        ),
    ]
