# Generated by Django 3.0.7 on 2020-06-07 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_historical_current'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historical',
            old_name='stock',
            new_name='stock_code',
        ),
    ]
