# Generated by Django 3.0.7 on 2020-06-07 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_auto_20200607_0153'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Historical',
            new_name='Position',
        ),
    ]
