# Generated by Django 3.0.7 on 2020-06-09 07:44

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0006_position_holding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='current',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='holding',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='series_x',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateField(null=True), size=None),
        ),
        migrations.AlterField(
            model_name='position',
            name='series_y',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(null=True), size=None),
        ),
    ]
