# Generated by Django 3.0.7 on 2020-06-09 07:46

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0007_auto_20200609_0744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='series_x',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateField(), size=None),
        ),
        migrations.AlterField(
            model_name='position',
            name='series_y',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), null=True, size=None),
        ),
    ]
