# Generated by Django 3.1.3 on 2020-11-20 23:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0009_position_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='buy_date',
            field=models.DateField(default=datetime.date(2020, 7, 1)),
            preserve_default=False,
        ),
    ]
