# Generated by Django 3.1.3 on 2020-11-21 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0010_position_buy_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='close_price',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='date_closed',
            field=models.DateField(null=True),
        ),
    ]
